[General]
Type=QML
Name=KAAL OS
Description=KAAL OS SDDM Login Theme
Screenshot=preview.png
ThemePath=/usr/share/sddm/themes/kaal

[Bindings]
; Left click anywhere to show login fields
LeftClick=showLogin
