#!/bin/bash
# KAAL OS — Systemd Target Generator
# Dynamically creates systemd targets and setup services for ALL spaces
# found in /etc/kaal/spaces/*.conf (including custom ones).
#
# This script runs:
# 1. At install time (post-install script 17)
# 2. When a new space is created/deleted (called by kaal-spaced)
# 3. Manually: kaal-space regenerate-targets

set -euo pipefail

SPACES_DIR="/etc/kaal/spaces"
SYSTEMD_DIR="/usr/lib/systemd/system"
APPLY_SCRIPT="/usr/libexec/kaal-spaces/apply-space.sh"

log() {
    logger -t kaal-spaces "$1"
    echo "[kaal-spaces] $1" >&2
}

# Built-in spaces that always have targets
BUILTIN="gaming development power normal"

# Find all space config files
find_spaces() {
    local spaces=()
    for conf in "$SPACES_DIR"/*.conf; do
        [[ -f "$conf" ]] || continue
        local basename
        basename=$(basename "$conf" .conf)
        # Skip auto-switch.conf
        [[ "$basename" == "auto-switch" ]] && continue
        # Validate name
        if echo "$basename" | grep -qE '^[a-z][a-z0-9-]{1,31}$'; then
            spaces+=("$basename")
        fi
    done
    echo "${spaces[@]}"
}

generate_target() {
    local space="$1"
    local target_file="${SYSTEMD_DIR}/kaal-space-${space}.target"
    local setup_file="${SYSTEMD_DIR}/kaal-space-${space}-setup.service"

    # Read display name from config
    local display_name
    display_name=$(awk -F= -v sec="\\[space\\]" -v key="name" '
        $0 ~ sec { in_section=1; next }
        /^\[/ { in_section=0 }
        in_section && $1 ~ "^\\s*" key "\\s*$" {
            gsub(/^\s+|\s+$/, "", $2)
            print $2
            exit
        }
    ' "${SPACES_DIR}/${space}.conf" 2>/dev/null || echo "$space")

    # Build conflicts list — all other spaces
    local all_spaces
    all_spaces=$(find_spaces)
    local conflicts=""
    for s in $all_spaces; do
        [[ "$s" != "$space" ]] && conflicts="${conflicts}kaal-space-${s}.target "
    done

    # Write target
    cat > "$target_file" << EOFTARGET
# Auto-generated by kaal-spaces target generator
# Do not edit — regenerate with: kaal-space regenerate-targets
[Unit]
Description=KAAL OS ${display_name} Space Target
AllowIsolate=yes
Conflicts=${conflicts}
Wants=kaal-space-${space}-setup.service
After=kaal-spaced.service

[Install]
WantedBy=multi-user.target
EOFTARGET

    # Write setup service
    cat > "$setup_file" << EOFSETUP
# Auto-generated by kaal-spaces target generator
[Unit]
Description=KAAL OS ${display_name} Space Setup
After=kaal-spaced.service
Before=graphical-session.target

[Service]
Type=oneshot
ExecStart=${APPLY_SCRIPT} ${space}
RemainAfterExit=yes

[Install]
WantedBy=kaal-space-${space}.target
EOFSETUP

    log "Generated target for space: ${space}"
}

# ============================================================================
# Main
# ============================================================================
log "Regenerating systemd targets for all spaces..."

# Ensure systemd directory exists
mkdir -p "$SYSTEMD_DIR"

# Remove old auto-generated targets
for f in "$SYSTEMD_DIR"/kaal-space-*.target "$SYSTEMD_DIR"/kaal-space-*-setup.service; do
    [[ -f "$f" ]] || continue
    if grep -q "Auto-generated" "$f" 2>/dev/null; then
        rm -f "$f"
    fi
done

# Generate targets for all discovered spaces
spaces=$(find_spaces)
count=0
for space in $spaces; do
    generate_target "$space"
    ((count++))
done

# Reload systemd
if command -v systemctl &>/dev/null; then
    systemctl daemon-reload 2>/dev/null || true
fi

log "Generated ${count} space targets"
echo "$count"
